[package]
name = "simplefs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { git = "https://github.com/rblaze/embedded-bytes.git", default-features = false }
